[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[metadata]
name = "dredd_webpgu_testing"
version = "0.0.1"

[tool.setuptools.packages]
find = {}  # Scan the project directory with the default parameters

[project]
name = "dredd_webgpu_testing"
version = "0.0.1"
authors = [
  { name="Amber Gorzynski", email="amber.gorzynski22@imperial.ac.uk" },
  { name="Alastair F. Donaldson", email="alastair.donaldson@imperial.ac.uk" },
]
description = "Runner scripts for research involving the Dredd mutation testing tool applied to WebGPU"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "numpy==2.2.2",
  "pandas==2.2.3",
  "path==17.0.0",
  "python-dateutil==2.9.0.post0",
  "pytz==2025.1",
  "six==1.17.0",
  "tzdata==2025.1",
  "Mako==1.3.8",
  "MarkupSafe==3.0.2",
  "meson==1.7.0",
  "ply==3.11",
  "PyYAML==6.0.2",
  "packaging=25.0",
]

