[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "cts-lab"
version = "0.1.0"
authors = [
  { name = "Amber Gorzynski", email = "amber.gorzynski22@imperial.ac.uk" },
  { name = "Alastair F. Donaldson", email = "alastair.donaldson@imperial.ac.uk" },
]
description = "Research tooling for analysis and augmentation of WebGPU Conformance Test Suites"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
  "numpy==2.2.2",
  "pandas==2.2.3",
  "path==17.0.0",
  "python-dateutil==2.9.0.post0",
  "pytz==2025.1",
  "six==1.17.0",
  "tzdata==2025.1",
  "Mako==1.3.8",
  "MarkupSafe==3.0.2",
  "meson==1.7.0",
  "ply==3.11",
  "PyYAML==6.0.2",
  "tqdm==4.67.1",
]

[project.scripts]
cts-lab = "cts_lab.cli:main"

[tool.setuptools.packages.find]
where = ["src"]