MIN_TIMEOUT_FOR_MUTANT_COMPILATION: float = 1.0
TIMEOUT_MULTIPLIER_FOR_MUTANT_COMPILATION: float = 5.0
MIN_TIMEOUT_FOR_MUTANT_EXECUTION: float = 1.0
TIMEOUT_MULTIPLIER_FOR_MUTANT_EXECUTION: float = 5.0
DEFAULT_COMPILATION_TIMEOUT: int = 5
DEFAULT_RUNTIME_TIMEOUT: int = 10
